//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.Resources.Membership {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MembershipMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MembershipMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSI.Resources.Membership.MembershipMessages", typeof(MembershipMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided language ID is not valid..
        /// </summary>
        public static string LanguageIdInvalid {
            get {
                return ResourceManager.GetString("LanguageIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language ISO code can only have 5 characters maximum..
        /// </summary>
        public static string LanguageIsCodeLenghtExceeded {
            get {
                return ResourceManager.GetString("LanguageIsCodeLenghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language with provided ISO code already exists..
        /// </summary>
        public static string LanguageISOCodeAlreadyExists {
            get {
                return ResourceManager.GetString("LanguageISOCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided language ISO code is not valid..
        /// </summary>
        public static string LanguageIsoCodeInvalid {
            get {
                return ResourceManager.GetString("LanguageIsoCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language ISO code is not provided. .
        /// </summary>
        public static string LanguageIsoCodeNotProvided {
            get {
                return ResourceManager.GetString("LanguageIsoCodeNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided language name is not valid..
        /// </summary>
        public static string LanguageNameInvalid {
            get {
                return ResourceManager.GetString("LanguageNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name can only have 30 characters maximum..
        /// </summary>
        public static string LanguageNameLenghtExceeded {
            get {
                return ResourceManager.GetString("LanguageNameLenghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name is not provided..
        /// </summary>
        public static string LanguageNameNotProvided {
            get {
                return ResourceManager.GetString("LanguageNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language details are not provided..
        /// </summary>
        public static string LanguageNotProvided {
            get {
                return ResourceManager.GetString("LanguageNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language with provided ID does not exist..
        /// </summary>
        public static string LanguageWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("LanguageWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module with provided code already exists..
        /// </summary>
        public static string ModuleCodeAlreadyExists {
            get {
                return ResourceManager.GetString("ModuleCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided module code is not valid..
        /// </summary>
        public static string ModuleCodeInvalid {
            get {
                return ResourceManager.GetString("ModuleCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module code can only have 100 characters maximum..
        /// </summary>
        public static string ModuleCodeLenghtExceeded {
            get {
                return ResourceManager.GetString("ModuleCodeLenghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided module ID is not valid..
        /// </summary>
        public static string ModuleIdInvalid {
            get {
                return ResourceManager.GetString("ModuleIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided module name is not valid..
        /// </summary>
        public static string ModuleNameInvalid {
            get {
                return ResourceManager.GetString("ModuleNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name can only have 100 characters maximum..
        /// </summary>
        public static string ModuleNameLenghtExceeded {
            get {
                return ResourceManager.GetString("ModuleNameLenghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module details are not provided..
        /// </summary>
        public static string ModuleNotProvided {
            get {
                return ResourceManager.GetString("ModuleNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module wit provided ID does not exist..
        /// </summary>
        public static string ModuleWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("ModuleWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission with provided code already exists..
        /// </summary>
        public static string PermissionCodeAlreadyExists {
            get {
                return ResourceManager.GetString("PermissionCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided permision code is not valid..
        /// </summary>
        public static string PermissionCodeInvalid {
            get {
                return ResourceManager.GetString("PermissionCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission code can only have 100 characters maximum..
        /// </summary>
        public static string PermissionCodeLenghtExceeded {
            get {
                return ResourceManager.GetString("PermissionCodeLenghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided permission ID is not valid..
        /// </summary>
        public static string PermissionIdInvalid {
            get {
                return ResourceManager.GetString("PermissionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission ID is not provided..
        /// </summary>
        public static string PermissionIdNotProvided {
            get {
                return ResourceManager.GetString("PermissionIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission details are not provided..
        /// </summary>
        public static string PermissionNotProvided {
            get {
                return ResourceManager.GetString("PermissionNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission with provided ID does not exist..
        /// </summary>
        public static string PermissionWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("PermissionWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided role ID does not exist..
        /// </summary>
        public static string RoleIdDoesNotExist {
            get {
                return ResourceManager.GetString("RoleIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided role ID is not valid..
        /// </summary>
        public static string RoleIdInvalid {
            get {
                return ResourceManager.GetString("RoleIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID is not provided..
        /// </summary>
        public static string RoleIdNotProvided {
            get {
                return ResourceManager.GetString("RoleIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role manipulation log ID is not provided..
        /// </summary>
        public static string RoleManipulationLogIdNotProvided {
            get {
                return ResourceManager.GetString("RoleManipulationLogIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role member already exist..
        /// </summary>
        public static string RoleMemberAlreadyExist {
            get {
                return ResourceManager.GetString("RoleMemberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role member ID is not valid..
        /// </summary>
        public static string RoleMemberIdInvalid {
            get {
                return ResourceManager.GetString("RoleMemberIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role member is not provided..
        /// </summary>
        public static string RoleMemberNotProvided {
            get {
                return ResourceManager.GetString("RoleMemberNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Member with provided ID does not exist..
        /// </summary>
        public static string RoleMemberWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("RoleMemberWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with provided name already exists..
        /// </summary>
        public static string RoleNameAlreadyExists {
            get {
                return ResourceManager.GetString("RoleNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name can only hace 50 characters maximum..
        /// </summary>
        public static string RoleNameLenghtExceeded {
            get {
                return ResourceManager.GetString("RoleNameLenghtExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is not provided..
        /// </summary>
        public static string RoleNameNotProvided {
            get {
                return ResourceManager.GetString("RoleNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role details are not provided..
        /// </summary>
        public static string RoleNotProvided {
            get {
                return ResourceManager.GetString("RoleNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permission with provided ID does not exist. .
        /// </summary>
        public static string RolePermissionIdDoesNotExist {
            get {
                return ResourceManager.GetString("RolePermissionIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permission with ID is invalid..
        /// </summary>
        public static string RolePermissionIdInvalid {
            get {
                return ResourceManager.GetString("RolePermissionIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role permission is not provided..
        /// </summary>
        public static string RolePermissionNotProvided {
            get {
                return ResourceManager.GetString("RolePermissionNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided tenant ID does not exist..
        /// </summary>
        public static string RoleTenantIdDoesNotExist {
            get {
                return ResourceManager.GetString("RoleTenantIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role tenant ID is not provided..
        /// </summary>
        public static string RoleTenantIdNotProvided {
            get {
                return ResourceManager.GetString("RoleTenantIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with provided ID does not exist..
        /// </summary>
        public static string RoleWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("RoleWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant wih provided identifier already exist..
        /// </summary>
        public static string TenantIdentifierAlreadyExists {
            get {
                return ResourceManager.GetString("TenantIdentifierAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant identifier is not provided..
        /// </summary>
        public static string TenantIdentifierNotProvided {
            get {
                return ResourceManager.GetString("TenantIdentifierNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided tenant ID is not valid..
        /// </summary>
        public static string TenantIdInvalid {
            get {
                return ResourceManager.GetString("TenantIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided tenant name is not valid..
        /// </summary>
        public static string TenantNameInvalid {
            get {
                return ResourceManager.GetString("TenantNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant name can only have 100 characters maximum..
        /// </summary>
        public static string TenantNameLengthExceeded {
            get {
                return ResourceManager.GetString("TenantNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant details are not provided..
        /// </summary>
        public static string TenantNotProvided {
            get {
                return ResourceManager.GetString("TenantNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant with provided ID does not exist..
        /// </summary>
        public static string TenantWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("TenantWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email is not valid..
        /// </summary>
        public static string UserEmailInvalid {
            get {
                return ResourceManager.GetString("UserEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email can only have 240 characters maximum..
        /// </summary>
        public static string UserEmailLengthExceeded {
            get {
                return ResourceManager.GetString("UserEmailLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User full name can only have 220 characters maximum..
        /// </summary>
        public static string UserFullNameLengthExceeded {
            get {
                return ResourceManager.GetString("UserFullNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identifier is not valid..
        /// </summary>
        public static string UserIdentifierInvalid {
            get {
                return ResourceManager.GetString("UserIdentifierInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identifier is not provided..
        /// </summary>
        public static string UserIdentifierNotProvided {
            get {
                return ResourceManager.GetString("UserIdentifierNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided user ID is not valid..
        /// </summary>
        public static string UserIdInvalid {
            get {
                return ResourceManager.GetString("UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User last name is not provided..
        /// </summary>
        public static string UserLastNameNotProvided {
            get {
                return ResourceManager.GetString("UserLastNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User middle name is not provided..
        /// </summary>
        public static string UserMiddleNameNotProvided {
            get {
                return ResourceManager.GetString("UserMiddleNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is not provided..
        /// </summary>
        public static string UserNameNotProvided {
            get {
                return ResourceManager.GetString("UserNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details are not provided. .
        /// </summary>
        public static string UserNotProvided {
            get {
                return ResourceManager.GetString("UserNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email already exist..
        /// </summary>
        public static string UserWithEmailExists {
            get {
                return ResourceManager.GetString("UserWithEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with provided ID does not exist..
        /// </summary>
        public static string UserWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with provided Identifier already exist..
        /// </summary>
        public static string UserWithIdentifierExists {
            get {
                return ResourceManager.GetString("UserWithIdentifierExists", resourceCulture);
            }
        }

        public static object NotAuthorizedAction { get; set; }
    }
}
