//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.Common.Resources.Document {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DocumentMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSI.Common.Resources.Document.DocumentMessages", typeof(DocumentMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;t any generator for given input and output data type..
        /// </summary>
        public static string ArgumentInvalidDocType {
            get {
                return ResourceManager.GetString("ArgumentInvalidDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input and/or output type is not specified..
        /// </summary>
        public static string ArgumentNullDocType {
            get {
                return ResourceManager.GetString("ArgumentNullDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document content not found..
        /// </summary>
        public static string DocumentContentNotFound {
            get {
                return ResourceManager.GetString("DocumentContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docx document could not be generated..
        /// </summary>
        public static string DocxGeneratorFailed {
            get {
                return ResourceManager.GetString("DocxGeneratorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML file could not be generated..
        /// </summary>
        public static string HtmlGeneratorFailed {
            get {
                return ResourceManager.GetString("HtmlGeneratorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document parameters not valid. Couldn&apos;t generate document..
        /// </summary>
        public static string InvalidDocumentFormat {
            get {
                return ResourceManager.GetString("InvalidDocumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON object could not be parsed..
        /// </summary>
        public static string JsonParsingFailed {
            get {
                return ResourceManager.GetString("JsonParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODT document could not be generated..
        /// </summary>
        public static string OdtGeneratorFailed {
            get {
                return ResourceManager.GetString("OdtGeneratorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF document could not be generated..
        /// </summary>
        public static string PDFGeneratorFailed {
            get {
                return ResourceManager.GetString("PDFGeneratorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined document.
        /// </summary>
        public static string UndefinedDocumentName {
            get {
                return ResourceManager.GetString("UndefinedDocumentName", resourceCulture);
            }
        }
    }
}
