//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.Resources.Notifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSI.Resources.Notifications.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not provided..
        /// </summary>
        public static string AttachmentFileNotProvided {
            get {
                return ResourceManager.GetString("AttachmentFileNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided attachment ID not valid..
        /// </summary>
        public static string AttachmentIdInvalid {
            get {
                return ResourceManager.GetString("AttachmentIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment not provided..
        /// </summary>
        public static string AttachmentNotProvided {
            get {
                return ResourceManager.GetString("AttachmentNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment with provided ID does not exist..
        /// </summary>
        public static string AttachmentWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("AttachmentWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object deleted..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided email message ID not valid..
        /// </summary>
        public static string EmailMessageIdInvalid {
            get {
                return ResourceManager.GetString("EmailMessageIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Message ID..
        /// </summary>
        public static string EmailMessageIdInvalidFormat {
            get {
                return ResourceManager.GetString("EmailMessageIdInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sender email format error..
        /// </summary>
        public static string EmailMessageInvalidFromFormat {
            get {
                return ResourceManager.GetString("EmailMessageInvalidFromFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid notification ID..
        /// </summary>
        public static string EmailMessageInvalidNotificationId {
            get {
                return ResourceManager.GetString("EmailMessageInvalidNotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification with provided ID does not exist..
        /// </summary>
        public static string EmailMessageNotificationWithIdDoesNotExists {
            get {
                return ResourceManager.GetString("EmailMessageNotificationWithIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Message is not provided..
        /// </summary>
        public static string EmailMessageNotProvided {
            get {
                return ResourceManager.GetString("EmailMessageNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email message successfully sent..
        /// </summary>
        public static string EmailMessageSent {
            get {
                return ResourceManager.GetString("EmailMessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email message with provided ID does not exist..
        /// </summary>
        public static string EmailMessageWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("EmailMessageWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification status ID not valid..
        /// </summary>
        public static string EmailNotificationStatusIdInvalid {
            get {
                return ResourceManager.GetString("EmailNotificationStatusIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient with provided email address already exists..
        /// </summary>
        public static string EmailRecipientAddressAlreadyExists {
            get {
                return ResourceManager.GetString("EmailRecipientAddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addres for recipient not provided.
        /// </summary>
        public static string EmailRecipientAddressEmpty {
            get {
                return ResourceManager.GetString("EmailRecipientAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address for recipient is not valid..
        /// </summary>
        public static string EmailRecipientAddressInvalid {
            get {
                return ResourceManager.GetString("EmailRecipientAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided email recipient ID is not valid..
        /// </summary>
        public static string EmailRecipientIdInvalid {
            get {
                return ResourceManager.GetString("EmailRecipientIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient details are not provided.
        /// </summary>
        public static string EmailRecipientNotProvided {
            get {
                return ResourceManager.GetString("EmailRecipientNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient type with provided code already exists..
        /// </summary>
        public static string EmailRecipientTypeCodeAlreadyExists {
            get {
                return ResourceManager.GetString("EmailRecipientTypeCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient type code can&apos;t be empty..
        /// </summary>
        public static string EmailRecipientTypeCodeEmpty {
            get {
                return ResourceManager.GetString("EmailRecipientTypeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient type code can only have 100 characters maximum..
        /// </summary>
        public static string EmailRecipientTypeCodeLengthExceeded {
            get {
                return ResourceManager.GetString("EmailRecipientTypeCodeLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided email recipient type ID not valid..
        /// </summary>
        public static string EmailRecipientTypeIdInvalid {
            get {
                return ResourceManager.GetString("EmailRecipientTypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient type name can only have 100 characters maximum..
        /// </summary>
        public static string EmailRecipientTypeNameLengthExceeded {
            get {
                return ResourceManager.GetString("EmailRecipientTypeNameLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient type details are not provided..
        /// </summary>
        public static string EmailRecipientTypeNotProvided {
            get {
                return ResourceManager.GetString("EmailRecipientTypeNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient type with provided ID does not exist..
        /// </summary>
        public static string EmailRecipientTypeWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("EmailRecipientTypeWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email recipient with provided ID does not exist..
        /// </summary>
        public static string EmailRecipientWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("EmailRecipientWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification create date not valid..
        /// </summary>
        public static string NotificationDateCreatedInvalid {
            get {
                return ResourceManager.GetString("NotificationDateCreatedInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification create date is not provided..
        /// </summary>
        public static string NotificationDateCreatedNotProvided {
            get {
                return ResourceManager.GetString("NotificationDateCreatedNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification external ID not valid..
        /// </summary>
        public static string NotificationExternalIdInvalid {
            get {
                return ResourceManager.GetString("NotificationExternalIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification external ID is not provided..
        /// </summary>
        public static string NotificationExternalIdNotProvided {
            get {
                return ResourceManager.GetString("NotificationExternalIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification ID not valid..
        /// </summary>
        public static string NotificationIdInvalid {
            get {
                return ResourceManager.GetString("NotificationIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification id not provided..
        /// </summary>
        public static string NotificationIdNotProvided {
            get {
                return ResourceManager.GetString("NotificationIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification details are not provided..
        /// </summary>
        public static string NotificationNotProvided {
            get {
                return ResourceManager.GetString("NotificationNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status code not provided..
        /// </summary>
        public static string NotificationStatusCodeNotProvided {
            get {
                return ResourceManager.GetString("NotificationStatusCodeNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status with provided ID does not exist..
        /// </summary>
        public static string NotificationStatusIdDoesNotExist {
            get {
                return ResourceManager.GetString("NotificationStatusIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status ID is not provided..
        /// </summary>
        public static string NotificationStatusIdNotProvided {
            get {
                return ResourceManager.GetString("NotificationStatusIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid notification status ID..
        /// </summary>
        public static string NotificationStatusInvalidId {
            get {
                return ResourceManager.GetString("NotificationStatusInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status name not provided..
        /// </summary>
        public static string NotificationStatusNameNotProvided {
            get {
                return ResourceManager.GetString("NotificationStatusNameNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status not provided..
        /// </summary>
        public static string NotificationStatusNotProvided {
            get {
                return ResourceManager.GetString("NotificationStatusNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status with provided code already exists..
        /// </summary>
        public static string NotificationStatusWCodeAlreadyExists {
            get {
                return ResourceManager.GetString("NotificationStatusWCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status with provided ID does not exists..
        /// </summary>
        public static string NotificationStatusWithIdDoesNotExists {
            get {
                return ResourceManager.GetString("NotificationStatusWithIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type code not provided..
        /// </summary>
        public static string NotificationTypeCodeEmpty {
            get {
                return ResourceManager.GetString("NotificationTypeCodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type with sam code exists in database..
        /// </summary>
        public static string NotificationTypeCodeExists {
            get {
                return ResourceManager.GetString("NotificationTypeCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification type ID not valid..
        /// </summary>
        public static string NotificationTypeIdInvalid {
            get {
                return ResourceManager.GetString("NotificationTypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type ID is not provided..
        /// </summary>
        public static string NotificationTypeIdNotProvided {
            get {
                return ResourceManager.GetString("NotificationTypeIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type name not provided..
        /// </summary>
        public static string NotificationTypeNameEmpty {
            get {
                return ResourceManager.GetString("NotificationTypeNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type details not provided..
        /// </summary>
        public static string NotificationTypeNotProvided {
            get {
                return ResourceManager.GetString("NotificationTypeNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type with provided ID dooes not exist..
        /// </summary>
        public static string NotificationTypeWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("NotificationTypeWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification user ID not valid..
        /// </summary>
        public static string NotificationUserIdInvalid {
            get {
                return ResourceManager.GetString("NotificationUserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification user is not provided..
        /// </summary>
        public static string NotificationUserNotProvided {
            get {
                return ResourceManager.GetString("NotificationUserNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationUser with provided ID does not exist..
        /// </summary>
        public static string NotificationUserWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("NotificationUserWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification with provided ID does not exist..
        /// </summary>
        public static string NotificationWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("NotificationWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SMS ID..
        /// </summary>
        public static string SmsInvalidId {
            get {
                return ResourceManager.GetString("SmsInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid notification ID..
        /// </summary>
        public static string SmsInvalidNotificationId {
            get {
                return ResourceManager.GetString("SmsInvalidNotificationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipent phone number format..
        /// </summary>
        public static string SmsInvalidPhoneNumberFormat {
            get {
                return ResourceManager.GetString("SmsInvalidPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sender phone number format..
        /// </summary>
        public static string SmsInvalidSenderPhoneNumberFormat {
            get {
                return ResourceManager.GetString("SmsInvalidSenderPhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification with provided ID does not exists..
        /// </summary>
        public static string SmsNotificationWithIdDoesNotExists {
            get {
                return ResourceManager.GetString("SmsNotificationWithIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS not provided..
        /// </summary>
        public static string SmsNotProvided {
            get {
                return ResourceManager.GetString("SmsNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS with provided ID does not exists..
        /// </summary>
        public static string SmsWithIdDoesNotExists {
            get {
                return ResourceManager.GetString("SmsWithIdDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided tenant ID not valid..
        /// </summary>
        public static string TenantIdInvalid {
            get {
                return ResourceManager.GetString("TenantIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant id not provided..
        /// </summary>
        public static string TenantIdNotProvided {
            get {
                return ResourceManager.GetString("TenantIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object updated..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided user ID not valid..
        /// </summary>
        public static string UserIdInvalid {
            get {
                return ResourceManager.GetString("UserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id not provided..
        /// </summary>
        public static string UserIdNotProvided {
            get {
                return ResourceManager.GetString("UserIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with provided ID does not exists..
        /// </summary>
        public static string UserWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with provided tenant ID does not exists..
        /// </summary>
        public static string UserWithTenantIdDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithTenantIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web notification date seen not provided..
        /// </summary>
        public static string WebNotificationDateSeenEmpty {
            get {
                return ResourceManager.GetString("WebNotificationDateSeenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided web notification ID not valid..
        /// </summary>
        public static string WebNotificationIdInvalid {
            get {
                return ResourceManager.GetString("WebNotificationIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided notification ID for web notification is not valid..
        /// </summary>
        public static string WebNotificationNotificationIdInvalid {
            get {
                return ResourceManager.GetString("WebNotificationNotificationIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web notification details not provided..
        /// </summary>
        public static string WebNotificationNotProvided {
            get {
                return ResourceManager.GetString("WebNotificationNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with provided ID in web notification request does not exist..
        /// </summary>
        public static string WebNotificationUserDoesNotExist {
            get {
                return ResourceManager.GetString("WebNotificationUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided ID for user in web notification request is invalid..
        /// </summary>
        public static string WebNotificationUserInfoIdInvalid {
            get {
                return ResourceManager.GetString("WebNotificationUserInfoIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web notification with provided ID does not exist..
        /// </summary>
        public static string WebNotificationWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("WebNotificationWithIdDoesNotExist", resourceCulture);
            }
        }
    }
}
