//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NsiContext : DbContext
    {
        public NsiContext()
            : base("name=NsiContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationLog> ApplicationLog { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<ManipulationLog> ManipulationLog { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleLanguage> ModuleLanguage { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<PermissionLanguage> PermissionLanguage { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMember> RoleMember { get; set; }
        public virtual DbSet<RolePermission> RolePermission { get; set; }
        public virtual DbSet<ScriptHistory> ScriptHistory { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
