//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionParameter()
        {
            this.RuleActionParameter = new HashSet<RuleActionParameter>();
        }
    
        public int ActionParameterId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int TenantId { get; set; }
        public int ActionId { get; set; }
        public int ActionParameterTypeId { get; set; }
    
        public virtual Action Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleActionParameter> RuleActionParameter { get; set; }
        public virtual ActionParameterType ActionParameterType { get; set; }
    }
}
