//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePropertyValue
    {
        public int DevicePropertyValueId { get; set; }
        public string PropertyValue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int TenantId { get; set; }
        public int DeviceId { get; set; }
        public int PropertyId { get; set; }
        public int DevicePingId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual DevicePing DevicePing { get; set; }
        public virtual Property Property { get; set; }
    }
}
