//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public int FileSize { get; set; }
        public System.Guid ExternalId { get; set; }
        public string LocationExternalId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int StorageTypeId { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public string Description { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual StorageType StorageType { get; set; }
    }
}
