//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailRecipient
    {
        public int EmailRecipientId { get; set; }
        public string EmailAddress { get; set; }
        public int EmaiMessagelId { get; set; }
        public int EmailRecipientTypeId { get; set; }
    
        public virtual EmailMessage EmailMessage { get; set; }
        public virtual EmailRecipientType EmailRecipientType { get; set; }
    }
}
