//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedDocument
    {
        public int GeneratedDocumentId { get; set; }
        public System.Guid ExternalId { get; set; }
        public string Name { get; set; }
        public bool Success { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Content { get; set; }
        public Nullable<int> TemplateVersionId { get; set; }
        public int DocumentTypeId { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual TemplateVersion TemplateVersion { get; set; }
    }
}
