//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentSettlement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncidentSettlement()
        {
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int IncidentSettlementId { get; set; }
        public string Description { get; set; }
        public string FullText { get; set; }
        public Nullable<System.DateTime> DateSettled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int TenantId { get; set; }
        public int IncidentStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
        public virtual IncidentStatus IncidentStatus { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
