//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NsiContext : DbContext
    {
        public NsiContext()
            : base("name=NsiContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ActionParameter> ActionParameter { get; set; }
        public virtual DbSet<ActionParameterType> ActionParameterType { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLog { get; set; }
        public virtual DbSet<Attachment> Attachment { get; set; }
        public virtual DbSet<Base> Base { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DevicePing> DevicePing { get; set; }
        public virtual DbSet<DevicePropertyValue> DevicePropertyValue { get; set; }
        public virtual DbSet<DeviceStatus> DeviceStatus { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<EmailMessage> EmailMessage { get; set; }
        public virtual DbSet<EmailRecipient> EmailRecipient { get; set; }
        public virtual DbSet<EmailRecipientType> EmailRecipientType { get; set; }
        public virtual DbSet<FakePingConfiguration> FakePingConfiguration { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<Folder> Folder { get; set; }
        public virtual DbSet<GeneratedDocument> GeneratedDocument { get; set; }
        public virtual DbSet<Incident> Incident { get; set; }
        public virtual DbSet<IncidentSettlement> IncidentSettlement { get; set; }
        public virtual DbSet<IncidentStatus> IncidentStatus { get; set; }
        public virtual DbSet<IncidentType> IncidentType { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<NotificationStatus> NotificationStatus { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleMember> RoleMember { get; set; }
        public virtual DbSet<RolePermission> RolePermission { get; set; }
        public virtual DbSet<Rule> Rule { get; set; }
        public virtual DbSet<RuleAction> RuleAction { get; set; }
        public virtual DbSet<RuleActionParameter> RuleActionParameter { get; set; }
        public virtual DbSet<RuleCondition> RuleCondition { get; set; }
        public virtual DbSet<ScriptHistory> ScriptHistory { get; set; }
        public virtual DbSet<Sms> Sms { get; set; }
        public virtual DbSet<StorageType> StorageType { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<TemplateVersion> TemplateVersion { get; set; }
        public virtual DbSet<Tenant> Tenant { get; set; }
        public virtual DbSet<TenantModule> TenantModule { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WebNotification> WebNotification { get; set; }
        public virtual DbSet<WorkOrder> WorkOrder { get; set; }
        public virtual DbSet<NotificationUser> NotificationUser { get; set; }
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
