//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleCondition
    {
        public int RuleConditionId { get; set; }
        public string ComparisonOperator { get; set; }
        public string ComparisonValue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
        public int TenantId { get; set; }
        public int DeviceId { get; set; }
        public int RuleId { get; set; }
        public int PropertyId { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Property Property { get; set; }
        public virtual Rule Rule { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
