//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleAction()
        {
            this.RuleActionParameter = new HashSet<RuleActionParameter>();
        }
    
        public int RuleActionId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
        public int TenantId { get; set; }
        public int RuleId { get; set; }
        public int DeviceId { get; set; }
        public int ActionId { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Device Device { get; set; }
        public virtual Rule Rule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleActionParameter> RuleActionParameter { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
