//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleActionParameter
    {
        public int RuleActionParameterId { get; set; }
        public string ParameterValue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public bool IsActive { get; set; }
        public int TenantId { get; set; }
        public int RuleActionId { get; set; }
        public int ActionParameterId { get; set; }
    
        public virtual ActionParameter ActionParameter { get; set; }
        public virtual RuleAction RuleAction { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
