//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TemplateVersion()
        {
            this.GeneratedDocument = new HashSet<GeneratedDocument>();
        }
    
        public int TemplateVersionId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsDefault { get; set; }
        public int TemplateId { get; set; }
        public string Content { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneratedDocument> GeneratedDocument { get; set; }
        public virtual Template Template { get; set; }
    }
}
