//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantModule
    {
        public int TenantModule1 { get; set; }
        public int TenantId { get; set; }
        public int ModuleId { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
