//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSI.Common.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided argument is not valid..
        /// </summary>
        public static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown input and/or output document type..
        /// </summary>
        public static string ArgumentInvalidDocType {
            get {
                return ResourceManager.GetString("ArgumentInvalidDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating document: Input and/or output document type not specified (null)..
        /// </summary>
        public static string ArgumentNullDocType {
            get {
                return ResourceManager.GetString("ArgumentNullDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name for filtering is not provided..
        /// </summary>
        public static string FilterColumnNameEmpty {
            get {
                return ResourceManager.GetString("FilterColumnNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided page is not valid..
        /// </summary>
        public static string InvalidPage {
            get {
                return ResourceManager.GetString("InvalidPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided records per page count is not valid..
        /// </summary>
        public static string InvalidRecordsPerPage {
            get {
                return ResourceManager.GetString("InvalidRecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paging parameter cannot be null..
        /// </summary>
        public static string PagingParameterNull {
            get {
                return ResourceManager.GetString("PagingParameterNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property with provided name does not exist..
        /// </summary>
        public static string PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not provided..
        /// </summary>
        public static string RequestNotProvided {
            get {
                return ResourceManager.GetString("RequestNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be found..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name for sorting is not provided..
        /// </summary>
        public static string SortColumnNameEmpty {
            get {
                return ResourceManager.GetString("SortColumnNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please try again later or contact support..
        /// </summary>
        public static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
    }
}
