//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSI.Common.Resources.TemplateManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateManagementMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateManagementMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSI.Common.Resources.TemplateManagement.TemplateManagementMessages", typeof(TemplateManagementMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with provided id does not exist..
        /// </summary>
        public static string FolderInvalidId {
            get {
                return ResourceManager.GetString("FolderInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name is not provided..
        /// </summary>
        public static string InvalidFolderName {
            get {
                return ResourceManager.GetString("InvalidFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template parameters not valid. Couldn&apos;t generate template..
        /// </summary>
        public static string InvalidTemplateFormat {
            get {
                return ResourceManager.GetString("InvalidTemplateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name is not provided..
        /// </summary>
        public static string InvalidTemplateName {
            get {
                return ResourceManager.GetString("InvalidTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template payload is not valid..
        /// </summary>
        public static string InvalidTemplatePayload {
            get {
                return ResourceManager.GetString("InvalidTemplatePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template type is not valid..
        /// </summary>
        public static string InvalidTemplateType {
            get {
                return ResourceManager.GetString("InvalidTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple default versions for requested template. .
        /// </summary>
        public static string MultipleDefaultTemplateVersions {
            get {
                return ResourceManager.GetString("MultipleDefaultTemplateVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template content is not provided..
        /// </summary>
        public static string TemplateContentEmpty {
            get {
                return ResourceManager.GetString("TemplateContentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new template failed..
        /// </summary>
        public static string TemplateCreationFailed {
            get {
                return ResourceManager.GetString("TemplateCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided argument is not valid..
        /// </summary>
        public static string TemplateInvalidArgument {
            get {
                return ResourceManager.GetString("TemplateInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template with provided id does not exist..
        /// </summary>
        public static string TemplateInvalidId {
            get {
                return ResourceManager.GetString("TemplateInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template version with provided id does not exist..
        /// </summary>
        public static string TemplateVersionInvalidId {
            get {
                return ResourceManager.GetString("TemplateVersionInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string UnexpectedProblem {
            get {
                return ResourceManager.GetString("UnexpectedProblem", resourceCulture);
            }
        }
    }
}
